### ISSUE TITLE
Where is declaration of dependency for Akka in build files?

### ISSUE THREAD

**Issue by nartamonov** [michaelahlers/sandbox-scala-js#1]
Hi, I see you use Akka in client side. I suppose it is Akka.js port, am I right? I can't find it in build dependencies.

**Comment by michaelahlers** [comment]
Hey @nartamonov, I wouldn't pay too much attention to this project—yet. It's mostly been a learning exercise, aiming for familiarity by (gradually) piecing together elements of @ochrons's _outstanding_ [Scala.js Single Page Application Tutorial](https://github.com/ochrons/scalajs-spa-tutorial). If you're aiming to ramp up on Scala.js, I'd start there. See also @andreaTP's game-changing [Akka.js project](https://github.com/akka-js/akka.js). Check back here later on, however, since I hope to illustrate a few interesting ideas involving the latter.

**Comment by nartamonov** [comment]
@michaelahlers ok, thanks for links! )

**Comment by michaelahlers** [comment]
Glad to help, @nartamonov, and thanks for the interest! I'll ping you once this project shapes up a bit. :wink:
